/users:
  get:
    parameters:
      - name: page
        in: query
        schema:
          type: integer

      - name: limit
        in: query
        schema:
          type: integer

      - name: search
        in: query
        schema:
          type: string